Controllers/PowerUnitsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;

namespace WebApp.Controllers
{
    public class PowerUnitsController : Controller
    {
        private readonly DataManager dataManager;

        public PowerUnitsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.PowerUnits.GetPowerUnitById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeword("PageServices"); // <----- Менять для моделей?
            return View(dataManager.PowerUnits.GetPowerUnits());
        }
    }
}

Controllers/ProcessorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;

namespace WebApp.Controllers
{
    public class ProcessorsController : Controller
    {
        private readonly DataManager dataManager;

        public ProcessorsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.Processors.GetProcessorById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeword("PageServices"); // <----- Менять для моделей?
            return View(dataManager.Processors.GetProcessors());
        }
    }
}

Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;

namespace WebApp.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index(Guid id)
        {
            if(id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeword("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

Controllers/SoundCardsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;

namespace WebApp.Controllers
{
    public class SoundCardsController : Controller
    {
        private readonly DataManager dataManager;

        public SoundCardsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.SoundCards.GetSoundCardById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeword("PageServices"); // <----- Менять для моделей?
            return View(dataManager.SoundCards.GetSoundCards());
        }
    }
}

Views/Shared/ChooseMotherboard.cshtml
@model IQueryable<Motherboard>

@{ 
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    <!--
    @Html.Raw(HttpContextAccessor.HttpContext.Request.Cookies["ProcessorId"])
    -->

    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (Motherboard item in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Motherboards" asp-action="Index" asp-route-id="@item.Id">
                        <img src="~/img/@item.TitleImagePath" class="left" />
                    </a>
                    <h4>@item.Title</h4>
                    <p>@item.Subtitle</p>

                    <form style="display: inline-block;" id="form-@item.Id" asp-area="" asp-controller="Components" asp-action="ChooseVideoadapter" asp-route-id="@item.Id" method="post">
                        <input type="hidden" name="MotherboardId" value="@item.Id" />
                        <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Добавить</a>
                    </form>
                </li>
            }
        </ul>
    }
</div>

Views/Shared/ChoosePowerUnit.cshtml
@model IQueryable<PowerUnit>

@{ 
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    @if (Model.Any())
    { 
        <ul class="big-image-list">
            @foreach (PowerUnit item in Model)
            { 
            <li>
                <a asp-area="" asp-controller="PowerUnits" asp-action="Index" asp-route-id="@item.Id">
                    <img src="~/img/@item.TitleImagePath" class="left" />
                </a>
                <h4>@item.Title</h4>
                <p>@item.Subtitle</p>

                <form style="display: inline-block;" id="form-@item.Id" asp-area="" asp-controller="Components" asp-action="EndComplictation" asp-route-id="@item.Id" method="post">
                    <input type="hidden" name="PowerUnitId" value="@item.Id" />
                    <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Добавить</a>
                </form>
            </li>
            }
        </ul>
    }
</div>

Views/Shared/ChooseProcessor.cshtml
@model IQueryable<Processor>

@{
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    @if (Model.Any())
    {
    <ul class="big-image-list">
        @foreach (Processor item in Model)
        {
        <li>
            <a asp-area="" asp-controller="Processors" asp-action="Index" asp-route-id="@item.Id">
                <img src="~/img/@item.TitleImagePath" class="left" />
            </a>
            <h4>@item.Title</h4>
            <p>@item.Subtitle</p>
            
            <form style="display: inline-block;" id="form-@item.Id" asp-area="" asp-controller="Components" asp-action="ChooseMotherboard" asp-route-id="@item.Id" method="post">
                <input type="hidden" name="ProcessorId" value="@item.Id" />
                <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Добавить</a>
            </form>
        </li>
        }
    </ul>
    }
</div>

Views/Shared/ChooseSoundCard.cshtml
@model IQueryable<SoundCard>

@{ 
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    @if (Model.Any())
    { 
        <ul class="big-image-list">
            @foreach (SoundCard item in Model)
            { 
            <li>
                <a asp-area="" asp-controller="SoundCards" asp-action="Index" asp-route-id="@item.Id">
                    <img src="~/img/@item.TitleImagePath" class="left" />
                </a>
                <h4>@item.Title</h4>
                <p>@item.Subtitle</p>

                <form style="display: inline-block;" id="form-@item.Id" asp-area="" asp-controller="Components" asp-action="ChooseStorageDevice" asp-route-id="@item.Id" method="post">
                    <input type="hidden" name="SoundCardId" value="@item.Id" />
                    <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Добавить</a>
                </form>
            </li>
            }
        </ul>
    }
</div>

Views/Shared/ChooseStorageDevice.cshtml
@model IQueryable<StorageDevice>

@{ 
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    @if (Model.Any())
    { 
        <ul class="big-image-list">
            @foreach (StorageDevice item in Model)
            { 
            <li>
                <a asp-area="" asp-controller="StorageDevices" asp-action="Index" asp-route-id="@item.Id">
                    <img src="~/img/@item.TitleImagePath" class="left" />
                </a>
                <h4>@item.Title</h4>
                <p>@item.Subtitle</p>

                <form style="display: inline-block;" id="form-@item.Id" asp-area="" asp-controller="Components" asp-action="ChoosePowerUnit" asp-route-id="@item.Id" method="post">
                    <input type="hidden" name="StorageDeviceId" value="@item.Id" />
                    <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Добавить</a>
                </form>
            </li>
            }
        </ul>
    }
</div>

Views/Shared/ChooseVideoadapter.cshtml
@model IQueryable<Videoadapter>

@{ 
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    @if (Model.Any())
    { 
        <ul class="big-image-list">
            @foreach (Videoadapter item in Model)
            { 
            <li>
                <a asp-area="" asp-controller="Videoadapters" asp-action="Index" asp-route-id="@item.Id">
                    <img src="~/img/@item.TitleImagePath" class="left" />
                </a>
                <h4>@item.Title</h4>
                <p>@item.Subtitle</p>

                <form style="display: inline-block;" id="form-@item.Id" asp-area="" asp-controller="Components" asp-action="ChooseSoundCard" asp-route-id="@item.Id" method="post">
                    <input type="hidden" name="VideoadapterId" value="@item.Id" />
                    <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Добавить</a>
                </form>
            </li>
            }
        </ul>
    }
</div>

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

Views/Shared/FooterPartial.cshtml
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-8 col-12-medium">

                <div id="copyrigth">
                    &copy; @Config.CompanyName. All rights reserved. | Design HTML5 UP
                </div>

            </div>
        </div>
    </div>
</div>

Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.CompanyName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Сервисы</a>
                        <a asp-area="" asp-controller="Components" asp-action="Index">Сборки</a>
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" asp-route-area="Admin">Админ панель</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

Views/Shared/MetaTagPartial.cshtml
@using WebApp.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description">
}

@if (ViewBag.KeyWords != null)
{
    <meta name="keywords" content="@ViewBag.KeyWords">
}

Views/Shared/ScriptsPartial.cshtml
<!-- Scripts -->
@*
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/browser.min.js"></script>
<script src="assets/js/breakpoints.min.js"></script>
<script src="assets/js/util.js"></script>
<script src="assets/js/main.js"></script> *@
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
    Minimaxing by HTML5 UP
    html5up.net | ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    @await Html.PartialAsync("MetaTagPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div id="page-wrapper">

        <!-- Header -->
        @await Html.PartialAsync("HeaderPartial")

        <!-- Main -->
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium imp-medium">

                        @RenderBody()

                    </div>
                    @await Html.PartialAsync("SidebarPartial")
                </div>
            </div>
        </div>

        <!-- Footer -->
        @await Html.PartialAsync("FooterPartial")

    </div>

    @await Html.PartialAsync("ScriptsPartial")

</body>
</html>