Areas/Admin/Controllers/StorageDeviceController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;
using WebApp.Domain.Entities;
using WebApp.Service;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StorageDevicesController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostEnvironment;

        public StorageDevicesController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
        {
            this.dataManager = dataManager;
            this.hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View(dataManager.StorageDevices.GetStorageDevices());
        }
        public IActionResult Edit(Guid id)
        {
            var item = id == default ? new StorageDevice() : dataManager.StorageDevices.GetStorageDeviceById(id);
            return View(item);
        }
        [HttpPost]
        public IActionResult Edit(StorageDevice model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "img/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                else if (!(model.TitleImagePath != null))
                {
                    model.TitleImagePath = "zero.png";
                }
                dataManager.StorageDevices.SaveStorageDevice(model);
                return RedirectToAction(nameof(StorageDevicesController.Index), nameof(StorageDevicesController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.StorageDevices.DeleteStorageDevice(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Controllers/StorageDevicesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;

namespace WebApp.Controllers
{
    public class StorageDevicesController : Controller
    {
        private readonly DataManager dataManager;

        public StorageDevicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.StorageDevices.GetStorageDeviceById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeword("PageServices"); // <----- Менять для моделей?
            return View(dataManager.StorageDevices.GetStorageDevices());
        }
    }
}

Views/StorageDevices/Index.cshtml
@model IQueryable<StorageDevice>

@{ 
    TextField textFiel = ViewBag.TextField;

    ViewBag.Title = textFiel.Title;
    ViewBag.Text = textFiel.Text;
}

<div class="div-box">
    @if (Model.Any())
    { 
        <ul class="big-image-list">
            @foreach (StorageDevice item in Model)
            { 
                <li>
                    <a asp-area="" asp-controller="StorageDevices" asp-action="Index" asp-route-id="@item.Id">
                        <img src="~/img/@item.TitleImagePath" class="left" />
                    </a>
                    <h4>@item.Title</h4>
                    <p>@item.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

Views/StorageDevices/Show.cshtml
@model StorageDevice

@{
    ViewBag.Title = Model.Title;
    ViewBag.Text = Model.Text;
}

<div class="div-box">
    <h2>
        @Model.Title
    </h2>
    <div> <img src="~/img/@Model.TitleImagePath" class="img-box" /> </div>
</div>

<div class="div-box">
    <bold>
        <label asp-for="Text"></label><br />
    </bold>
    @Html.Raw(Model.Text)
</div>

<div class="div-box">
    <bold>
        <label asp-for="FormFactor"></label><br />
    </bold>
    <p>@Model.FormFactor</p>
</div>

<div class="div-box">
    <bold>
        <label asp-for="ModelName"></label><br />
    </bold>
    <p>@Model.ModelName</p>
</div>

<div class="div-box">
    <bold>
        <label asp-for="DateCreated"></label><br />
    </bold>
    <p>@Model.DateCreated</p>
</div>

<div class="div-box">
    <bold>
        <label asp-for="Maker"></label><br />
    </bold>
    <p>@Model.Maker</p>
</div>

<div class="div-box">
    <bold>
        <label asp-for="Price"></label><br />
    </bold>
    <p>@Model.Price</p>
</div>