Areas/Admin/Controllers/MotherboardsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;
using WebApp.Domain.Entities;
using WebApp.Service;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MotherboardsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostEnvironment;

        public MotherboardsController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
        {
            this.dataManager = dataManager;
            this.hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View(dataManager.Motherboards.GetMotherboards());
        }
        public IActionResult Edit(Guid id)
        {
            var item = id == default ? new Motherboard() : dataManager.Motherboards.GetMotherboardById(id);
            return View(item);
        }
        [HttpPost]
        public IActionResult Edit(Motherboard model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "img/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                else if (!(model.TitleImagePath != null))
                {
                    model.TitleImagePath = "zero.png";
                }
                dataManager.Motherboards.SaveMotherboard(model);
                return RedirectToAction(nameof(MotherboardsController.Index), nameof(MotherboardsController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Motherboards.DeleteMotherboard(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Controllers/MotherboardsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain;

namespace WebApp.Controllers
{
    public class MotherboardsController : Controller
    {
        private readonly DataManager dataManager;

        public MotherboardsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.Motherboards.GetMotherboardById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeword("PageServices"); // <-- ? менять ли для моделей (Добавляет название окну)
            return View(dataManager.Motherboards.GetMotherboards());
        }
    }
}

Areas/Admin/Views/Motherboards/Edit.cshtml
@model Motherboard

@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="/js/ckeditor_4.16.2_standard/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div class="div-box">
        <form asp-area="Admin" asp-controller="Motherboards" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdd" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label><br />
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label><br />
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="ProcessorSocket"></label><br />
                <input asp-for="ProcessorSocket" />
                <span asp-validation-for="ProcessorSocket"></span>
            </div>
            <div class="div-box">
                <label asp-for="VideoadapterInterface"></label><br />
                <input asp-for="VideoadapterInterface" />
                <span asp-validation-for="VideoadapterInterface"></span>
            </div>
            <div class="div-box">
                <label asp-for="FormFactorStorageDevice"></label><br />
                <input asp-for="FormFactorStorageDevice" />
                <span asp-validation-for="FormFactorStorageDevice"></span>
            </div>
            <div class="div-box">
                <label asp-for="FormFactorPowerUnit"></label><br />
                <input asp-for="FormFactorPowerUnit" />
                <span asp-validation-for="FormFactorPowerUnit"></span>
            </div>
            <div class="div-box">
                <label asp-for="FormFactorSoundCard"></label><br />
                <input asp-for="FormFactorSoundCard" />
                <span asp-validation-for="FormFactorSoundCard"></span>
            </div>
            <div class="div-box">
                <label asp-for="ModelName"></label><br />
                <input asp-for="ModelName" />
                <span asp-validation-for="ModelName"></span>
            </div>
            <div class="div-box">
                <label asp-for="DateCreated"></label><br />
                <input asp-for="DateCreated" />
                <span asp-validation-for="DateCreated"></span>
            </div>
            <div class="div-box">
                <label asp-for="Maker"></label><br />
                <input asp-for="Maker" />
                <span asp-validation-for="Maker"></span>
            </div>
            <div class="div-box">
                <label asp-for="Price"></label><br />
                <input asp-for="Price" />
                <span asp-validation-for="Price"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label><br />
                <textarea id="TextEditArea" asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label><br />
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-box" src="~/img/@Model.TitleImagePath" />
                </div>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var editor = CKEDITOR.replace('TextEditArea');
    });
</script>

Areas/Admin/Views/Motherboards/Index.cshtml
@model IQueryable<Motherboard>


@{
    string strTitle = "Редактировать материнские платы";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши материнские платы</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="Motherboards" asp-action="Edit" asp-route-id=""> Добавить материнскую плату </a>
        </div>
        @if (@Model.Any())
        {
            <div>
                <ul>
                    @foreach (Motherboard item in Model)
                    {
                        <li>
                            <a asp-area="Admin" asp-controller="Motherboards" asp-action="Edit" asp-route-id="@item.Id">Редактировать</a>
                            <form style="display: inline-block;" id="form-@item.Id" asp-area="Admin" asp-controller="Motherboards" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                <input type="hidden" name="id" value="@item.Id" />
                                <a href="#" onclick="document.getElementById('form-@item.Id').submit()">Удалить</a>
                            </form>

                            <a asp-area="" asp-controller="Motherboards" asp-action="Index" asp-route-id="@item.Id">@($"{item.Title}")</a>
                        </li>
                    }
                </ul>
            </div>
        }
    </div>
</div>